name: Get Secrets Workflow

on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      API_ENDPOINT:
        description: "Name of the first secret"
        required: true
      API_KEY:
        description: "Name of the second secret"
        required: true
      PROJECT_ID:
        description: "Name of the third secret"
        required: true

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Retrieve Secrets
        env:
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
          API_KEY: ${{ secrets.API_KEY }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          echo "Retrieving Secrets..."
          echo "First Secret: $API_ENDPOINT"
          echo "Second Secret: $API_KEY"
          echo "Third Secret: $PROJECT_ID"
